/*
  AGS Digital Store — data-first catalog
  Replace/add objects in this file to scale the store. No UI file needs editing.
  affiliateUrl should only be populated when you have a valid affiliate/tracking URL.
*/

export const categories = [
  {id:'hosting', name:'Hosting & Cloud', icon:'☁️', description:'Web hosting, cloud infrastructure and deployment services.'},
  {id:'seo', name:'Marketing & SEO', icon:'📈', description:'SEO, content and digital marketing platforms.'},
  {id:'ai', name:'AI & Automation', icon:'🤖', description:'AI assistants, automation and intelligent workflows.'},
  {id:'ecommerce', name:'Ecommerce', icon:'🛒', description:'Online store, commerce and merchant platforms.'},
  {id:'design', name:'Design & Creator', icon:'🎨', description:'Design, creative workflow and creator platforms.'},
  {id:'productivity', name:'Productivity', icon:'📋', description:'Planning, documentation, collaboration and productivity.'},
  {id:'security', name:'Security & Privacy', icon:'🔐', description:'Security, privacy, identity and network protection.'},
  {id:'development', name:'Website & Development', icon:'💻', description:'Web development, builders, deployment and developer tools.'},
  {id:'crm', name:'Email & CRM', icon:'📧', description:'CRM, email marketing and customer engagement platforms.'},
  {id:'analytics', name:'Analytics & Data', icon:'📊', description:'Analytics, insights, dashboards and data products.'},
  {id:'business', name:'Business & Finance', icon:'💼', description:'Business operations, finance, proposals and team services.'},
  {id:'digital-products', name:'Digital Products', icon:'📦', description:'Templates, assets, marketplaces and downloadable digital products.'}
];

const brand = (id,name,category,description,tags,officialUrl,extra={}) => ({
  id, slug:id, name, logo:null, description, category, subcategory:category,
  tags, keywords:[name.toLowerCase(), ...tags.map(t=>t.toLowerCase())],
  useCases:['Business'], pricing:'paid', pricingLabel:'Premium', freeTrial:false,
  rating:null, badges:[], features:[], pros:[], cons:[], officialUrl, affiliateUrl:'',
  featured:false,popular:false,trending:false,deal:false, ...extra
});

export const brands = [
brand('hostinger','Hostinger','hosting','Web hosting and website services for individuals, creators and businesses.',['Hosting','Websites','Domains'],'https://www.hostinger.com/',{badges:['Popular'],featured:true,popular:true,pricingLabel:'Paid',useCases:['Business','Creator','Ecommerce']}),
brand('cloudways','Cloudways','hosting','Managed cloud hosting platform for deploying and managing websites and applications.',['Cloud','Hosting','Managed Hosting'],'https://www.cloudways.com/',{popular:true,useCases:['Business','Developer','Agency']}),
brand('kinsta','Kinsta','hosting','Managed hosting platform focused on WordPress and applications.',['WordPress','Managed Hosting','Cloud'],'https://kinsta.com/',{featured:true,useCases:['Business','Developer','Agency']}),
brand('siteground','SiteGround','hosting','Web hosting services for websites, WordPress and online projects.',['Hosting','WordPress','Websites'],'https://www.siteground.com/',{popular:true,useCases:['Business','Creator','Ecommerce']}),
brand('digitalocean','DigitalOcean','hosting','Cloud infrastructure and developer services for applications and workloads.',['Cloud','Developer','Infrastructure'],'https://www.digitalocean.com/',{featured:true,useCases:['Developer','Business']}),
brand('vultr','Vultr','hosting','Cloud compute and infrastructure services for developers and businesses.',['Cloud','Compute','Developer'],'https://www.vultr.com/',{useCases:['Developer','Business']}),
brand('linode','Linode','hosting','Cloud computing and developer infrastructure from Akamai.',['Cloud','Compute','Linux'],'https://www.linode.com/',{useCases:['Developer','Business']}),
brand('aws','Amazon Web Services','hosting','Cloud computing platform offering infrastructure and managed cloud services.',['Cloud','Infrastructure','Developer'],'https://aws.amazon.com/',{useCases:['Developer','Business','Agency']}),
brand('google-cloud','Google Cloud','hosting','Cloud platform for infrastructure, data, AI and application services.',['Cloud','AI','Infrastructure'],'https://cloud.google.com/',{useCases:['Developer','Business']}),
brand('microsoft-azure','Microsoft Azure','hosting','Cloud platform for computing, storage, data and application services.',['Cloud','Infrastructure','Developer'],'https://azure.microsoft.com/',{useCases:['Developer','Business']}),
brand('vercel','Vercel','development','Platform for deploying modern web applications and frontend experiences.',['Deployment','Frontend','Cloud'],'https://vercel.com/',{badges:['Popular'],popular:true,useCases:['Developer','Business']}),
brand('netlify','Netlify','development','Platform for building, deploying and operating modern web experiences.',['Deployment','Jamstack','Frontend'],'https://www.netlify.com/',{popular:true,useCases:['Developer','Business']}),
brand('github','GitHub','development','Developer platform for code hosting, collaboration and software delivery.',['Code','Git','Collaboration'],'https://github.com/',{badges:['Popular'],popular:true,useCases:['Developer','Business','Student']}),
brand('gitlab','GitLab','development','DevSecOps platform for source code, CI/CD and team collaboration.',['Git','CI/CD','DevSecOps'],'https://about.gitlab.com/',{useCases:['Developer','Business']}),
brand('bitbucket','Bitbucket','development','Git-based code hosting and collaboration platform from Atlassian.',['Git','Code','Collaboration'],'https://bitbucket.org/',{useCases:['Developer','Business']}),
brand('webflow','Webflow','development','Visual website platform combining site building, CMS and publishing workflows.',['Website Builder','CMS','Design'],'https://webflow.com/',{badges:['Popular'],featured:true,popular:true,useCases:['Creator','Business','Agency']}),
brand('wordpress','WordPress.com','development','Hosted WordPress platform for websites, publishing and online projects.',['WordPress','CMS','Websites'],'https://wordpress.com/',{popular:true,useCases:['Creator','Business','Blogger']}),
brand('elementor','Elementor','development','Visual WordPress website builder and design platform.',['WordPress','Website Builder','Design'],'https://elementor.com/',{popular:true,useCases:['Creator','Agency','Business']}),
brand('wix','Wix','development','Website platform for creating and managing websites and online services.',['Website Builder','CMS','Business'],'https://www.wix.com/',{badges:['Popular'],popular:true,useCases:['Business','Creator','Ecommerce']}),
brand('squarespace','Squarespace','development','Website and commerce platform for creators, businesses and online brands.',['Website Builder','Commerce','Design'],'https://www.squarespace.com/',{popular:true,useCases:['Creator','Business','Ecommerce']}),
brand('semrush','Semrush','seo','Digital marketing platform covering SEO, research and marketing workflows.',['SEO','Keywords','Marketing','Research'],'https://www.semrush.com/',{badges:['Popular','Premium'],featured:true,popular:true,freeTrial:true,useCases:['Business','Agency','Marketing']}),
brand('ahrefs','Ahrefs','seo','SEO and content marketing platform for research, analysis and site insights.',['SEO','Keywords','Backlinks','Content'],'https://ahrefs.com/',{badges:['Popular'],popular:true,useCases:['Business','Agency','Marketing']}),
brand('se-ranking','SE Ranking','seo','SEO platform for rank tracking, research and website analysis.',['SEO','Rank Tracking','Analytics'],'https://seranking.com/',{useCases:['Business','Agency','Marketing']}),
brand('mangools','Mangools','seo','SEO toolkit focused on keyword research, rankings and SERP analysis.',['SEO','Keywords','SERP'],'https://mangools.com/',{useCases:['Marketing','Creator','Business']}),
brand('surfer','Surfer','seo','Content optimization platform for SEO-focused content workflows.',['SEO','Content','Optimization'],'https://surferseo.com/',{useCases:['Marketing','Agency','Creator']}),
brand('moz','Moz','seo','SEO software and resources for search visibility and site analysis.',['SEO','Keywords','Rank Tracking'],'https://moz.com/',{useCases:['Marketing','Agency','Business']}),
brand('screaming-frog','Screaming Frog','seo','SEO software for technical website crawling and analysis.',['Technical SEO','Crawler','Audit'],'https://www.screamingfrog.co.uk/seo-spider/',{useCases:['Developer','Agency','Marketing']}),
brand('yoast','Yoast','seo','SEO tools and education for WordPress and broader search optimization workflows.',['SEO','WordPress','Content'],'https://yoast.com/',{useCases:['Creator','Business','Marketing']}),
brand('hubspot','HubSpot','crm','Customer platform covering CRM, marketing, sales and service workflows.',['CRM','Marketing','Sales','Service'],'https://www.hubspot.com/',{badges:['Popular'],featured:true,popular:true,pricingLabel:'Freemium',pricing:'freemium',useCases:['Business','Agency','Marketing']}),
brand('salesforce','Salesforce','crm','CRM platform for sales, service, marketing and customer operations.',['CRM','Sales','Service'],'https://www.salesforce.com/',{popular:true,useCases:['Business','Agency']}),
brand('activecampaign','ActiveCampaign','crm','Customer engagement platform focused on marketing automation, email and CRM.',['Email','Automation','CRM'],'https://www.activecampaign.com/',{popular:true,useCases:['Business','Marketing','Agency']}),
brand('aweber','AWeber','crm','Email marketing and automation platform for creators and businesses.',['Email','Marketing','Automation'],'https://www.aweber.com/',{useCases:['Creator','Business','Marketing']}),
brand('kit','Kit','crm','Creator-focused email platform for newsletters, products and audience growth.',['Email','Creator','Newsletter'],'https://kit.com/',{pricingLabel:'Freemium',pricing:'freemium',popular:true,useCases:['Creator','Business']}),
brand('mailchimp','Mailchimp','crm','Marketing automation and email platform for growing businesses.',['Email','Marketing','Automation'],'https://mailchimp.com/',{pricingLabel:'Freemium',pricing:'freemium',popular:true,useCases:['Business','Marketing']}),
brand('convertkit','ConvertKit','crm','Email and creator marketing platform now operating under the Kit brand.',['Email','Creator','Newsletter'],'https://convertkit.com/',{pricingLabel:'Freemium',pricing:'freemium',useCases:['Creator','Business']}),
brand('pipedrive','Pipedrive','crm','Sales CRM platform for managing deals, pipelines and sales activity.',['CRM','Sales','Pipeline'],'https://www.pipedrive.com/',{useCases:['Business','Agency']}),
brand('zoho-crm','Zoho CRM','crm','CRM platform for sales teams and business customer operations.',['CRM','Sales','Business'],'https://www.zoho.com/crm/',{useCases:['Business','Agency']}),
brand('notion','Notion','productivity','Workspace for notes, docs, projects, databases and team knowledge.',['Notes','Docs','Projects','Workspace'],'https://www.notion.so/',{badges:['Popular'],featured:true,popular:true,pricingLabel:'Freemium',pricing:'freemium',useCases:['Business','Creator','Student']}),
brand('clickup','ClickUp','productivity','Project management and productivity platform for tasks, docs and team workflows.',['Projects','Tasks','Collaboration'],'https://clickup.com/',{badges:['Popular'],popular:true,pricingLabel:'Freemium',pricing:'freemium',useCases:['Business','Agency','Developer']}),
brand('airtable','Airtable','productivity','Flexible database and workflow platform for organizing business data and processes.',['Database','Workflow','Collaboration'],'https://www.airtable.com/',{pricingLabel:'Freemium',pricing:'freemium',useCases:['Business','Agency','Creator']}),
brand('miro','Miro','productivity','Visual collaboration workspace for brainstorming, mapping and team planning.',['Whiteboard','Collaboration','Planning'],'https://miro.com/',{popular:true,pricingLabel:'Freemium',pricing:'freemium',useCases:['Business','Agency','Student']}),
brand('asana','Asana','productivity','Work management platform for projects, tasks and team coordination.',['Project Management','Tasks','Teams'],'https://asana.com/',{popular:true,pricingLabel:'Freemium',pricing:'freemium',useCases:['Business','Agency']}),
brand('trello','Trello','productivity','Visual project management using boards, lists and cards.',['Boards','Tasks','Projects'],'https://trello.com/',{popular:true,pricingLabel:'Freemium',pricing:'freemium',useCases:['Business','Creator','Student']}),
brand('slack','Slack','productivity','Team communication and collaboration platform organized around channels.',['Chat','Teams','Collaboration'],'https://slack.com/',{badges:['Popular'],popular:true,pricingLabel:'Freemium',pricing:'freemium',useCases:['Business','Agency','Developer']}),
brand('linear','Linear','productivity','Issue tracking and project management platform for product and engineering teams.',['Issues','Product','Engineering'],'https://linear.app/',{useCases:['Developer','Business']}),
brand('basecamp','Basecamp','productivity','Project management and team communication platform.',['Projects','Communication','Teams'],'https://basecamp.com/',{useCases:['Business','Agency']}),
brand('google-workspace','Google Workspace','productivity','Suite of cloud productivity and collaboration tools for organizations.',['Docs','Drive','Email','Collaboration'],'https://workspace.google.com/',{popular:true,useCases:['Business','Student','Creator']}),
brand('canva','Canva','design','Visual design platform for presentations, social content, documents and more.',['Design','Templates','Graphics','Creator'],'https://www.canva.com/',{badges:['Popular'],featured:true,popular:true,pricingLabel:'Freemium',pricing:'freemium',useCases:['Creator','Business','Student']}),
brand('figma','Figma','design','Collaborative interface design and prototyping platform.',['UI Design','Prototype','Collaboration'],'https://www.figma.com/',{badges:['Popular'],popular:true,pricingLabel:'Freemium',pricing:'freemium',useCases:['Designer','Developer','Business']}),
brand('adobe-creative-cloud','Adobe Creative Cloud','design','Creative software subscription platform spanning design, photo, video and creative work.',['Design','Photo','Video','Creative'],'https://www.adobe.com/creativecloud.html',{popular:true,useCases:['Creator','Designer','Agency']}),
brand('envato','Envato','digital-products','Marketplace and subscription ecosystem for digital assets, templates and creative resources.',['Templates','Assets','Creative'],'https://www.envato.com/',{badges:['Popular'],popular:true,useCases:['Creator','Agency','Developer']}),
brand('freepik','Freepik','design','Library of graphic resources, stock assets and creative design resources.',['Graphics','Stock','Templates'],'https://www.freepik.com/',{popular:true,pricingLabel:'Freemium',pricing:'freemium',useCases:['Creator','Designer','Agency']}),
brand('dribbble','Dribbble','design','Creative community and platform for discovering and showcasing design work.',['Design','Community','Inspiration'],'https://dribbble.com/',{useCases:['Designer','Creator']}),
brand('behance','Behance','design','Creative portfolio and discovery platform for designers and artists.',['Portfolio','Design','Creative'],'https://www.behance.net/',{pricing:'free',pricingLabel:'Free',useCases:['Designer','Creator']}),
brand('loom','Loom','design','Video messaging platform for recording and sharing concise screen and camera videos.',['Video','Screen Recording','Communication'],'https://www.loom.com/',{pricing:'freemium',pricingLabel:'Freemium',useCases:['Business','Creator','Developer']}),
brand('descript','Descript','design','Audio and video editing platform built around text-based media workflows.',['Video','Audio','Creator','AI'],'https://www.descript.com/',{pricing:'freemium',pricingLabel:'Freemium',useCases:['Creator','Agency']}),
brand('shopify','Shopify','ecommerce','Commerce platform for building and operating online stores.',['Ecommerce','Store Builder','Payments'],'https://www.shopify.com/',{badges:['Popular'],featured:true,popular:true,useCases:['Ecommerce','Business']}),
brand('ecwid','Ecwid','ecommerce','Online store tools that can be added to existing websites and channels.',['Ecommerce','Store','Online Selling'],'https://www.ecwid.com/',{pricing:'freemium',pricingLabel:'Freemium',useCases:['Ecommerce','Business']}),
brand('woocommerce','WooCommerce','ecommerce','Open-source ecommerce platform for WordPress websites.',['Ecommerce','WordPress','Online Store'],'https://woocommerce.com/',{popular:true,useCases:['Ecommerce','Developer','Business']}),
brand('bigcommerce','BigCommerce','ecommerce','Ecommerce platform for growing and established online businesses.',['Ecommerce','B2B','Online Store'],'https://www.bigcommerce.com/',{useCases:['Ecommerce','Business']}),
brand('wix-ecommerce','Wix Ecommerce','ecommerce','Ecommerce capabilities within the Wix website platform.',['Ecommerce','Website Builder','Store'],'https://www.wix.com/ecommerce', {useCases:['Ecommerce','Business','Creator']}),
brand('squarespace-commerce','Squarespace Commerce','ecommerce','Commerce tools within the Squarespace website platform.',['Ecommerce','Store','Creator'],'https://www.squarespace.com/ecommerce', {useCases:['Ecommerce','Creator','Business']}),
brand('sellfy','Sellfy','ecommerce','Platform for selling digital products, subscriptions and merchandise online.',['Digital Products','Store','Creators'],'https://sellfy.com/',{useCases:['Creator','Ecommerce']}),
brand('gumroad','Gumroad','ecommerce','Platform for creators to sell digital products and memberships directly to audiences.',['Digital Products','Creators','Memberships'],'https://gumroad.com/',{useCases:['Creator','Ecommerce']}),
brand('podia','Podia','ecommerce','Platform for selling digital downloads, courses, memberships and email products.',['Courses','Digital Products','Memberships'],'https://www.podia.com/',{useCases:['Creator','Ecommerce']}),
brand('teachable','Teachable','ecommerce','Platform for creators and businesses to publish and sell online courses.',['Courses','Education','Creator'],'https://teachable.com/',{useCases:['Creator','Business']}),
brand('chatgpt','ChatGPT','ai','AI assistant platform for writing, research, coding and general productivity workflows.',['AI','Assistant','Writing','Coding'],'https://chatgpt.com/',{badges:['Popular'],featured:true,popular:true,pricing:'freemium',pricingLabel:'Freemium',freeTrial:true,useCases:['Business','Creator','Developer','Student']}),
brand('claude','Claude','ai','AI assistant from Anthropic for writing, analysis, coding and knowledge work.',['AI','Assistant','Writing','Coding'],'https://claude.ai/',{badges:['Popular'],popular:true,pricing:'freemium',pricingLabel:'Freemium',useCases:['Business','Developer','Creator','Student']}),
brand('gemini','Gemini','ai','Google AI assistant for writing, reasoning, research and productivity tasks.',['AI','Assistant','Research','Productivity'],'https://gemini.google.com/',{badges:['Popular'],popular:true,pricing:'freemium',pricingLabel:'Freemium',useCases:['Business','Student','Creator']}),
brand('perplexity','Perplexity','ai','AI-powered answer and research platform for web-oriented information discovery.',['AI','Research','Search'],'https://www.perplexity.ai/',{badges:['Popular'],popular:true,pricing:'freemium',pricingLabel:'Freemium',useCases:['Student','Business','Research']}),
brand('jasper','Jasper','ai','AI platform focused on marketing and content workflows.',['AI','Marketing','Content'],'https://www.jasper.ai/',{useCases:['Marketing','Agency','Business']}),
brand('copy-ai','Copy.ai','ai','AI-powered platform for content and go-to-market workflows.',['AI','Content','Marketing'],'https://www.copy.ai/',{pricing:'freemium',pricingLabel:'Freemium',useCases:['Marketing','Business','Agency']}),
brand('grammarly','Grammarly','ai','Writing assistance platform for clarity, correctness and communication workflows.',['Writing','AI','Productivity'],'https://www.grammarly.com/',{badges:['Popular'],popular:true,pricing:'freemium',pricingLabel:'Freemium',useCases:['Student','Business','Creator']}),
brand('zapier','Zapier','ai','Automation platform for connecting apps and automating workflows.',['Automation','Integrations','No-Code'],'https://zapier.com/',{badges:['Popular'],featured:true,popular:true,pricing:'freemium',pricingLabel:'Freemium',useCases:['Business','Agency','Creator']}),
brand('make','Make','ai','Visual workflow automation and integration platform.',['Automation','Integrations','Workflow'],'https://www.make.com/',{pricing:'freemium',pricingLabel:'Freemium',useCases:['Business','Developer','Agency']}),
brand('n8n','n8n','ai','Workflow automation platform for connecting services and building automations.',['Automation','Workflow','Developer'],'https://n8n.io/',{pricing:'freemium',pricingLabel:'Freemium',useCases:['Developer','Business']}),
brand('replit','Replit','development','Browser-based development environment for creating and deploying software.',['Coding','AI','Cloud','Development'],'https://replit.com/',{pricing:'freemium',pricingLabel:'Freemium',popular:true,useCases:['Developer','Student']}),
brand('cursor','Cursor','development','AI-assisted code editor designed for software development workflows.',['Coding','AI','Developer'],'https://www.cursor.com/',{popular:true,useCases:['Developer']}),
brand('postman','Postman','development','API platform for building, testing and collaborating on APIs.',['API','Developer','Testing'],'https://www.postman.com/',{popular:true,pricing:'freemium',pricingLabel:'Freemium',useCases:['Developer','Business']}),
brand('jetbrains','JetBrains','development','Developer tools and integrated development environments for software engineering.',['IDE','Developer','Coding'],'https://www.jetbrains.com/',{useCases:['Developer','Student']}),
brand('docker','Docker','development','Container platform and tooling for software development and deployment.',['Containers','Developer','DevOps'],'https://www.docker.com/',{popular:true,pricing:'freemium',pricingLabel:'Freemium',useCases:['Developer','Business']}),
brand('cloudflare','Cloudflare','security','Network, performance and security services for internet properties.',['Security','CDN','DNS','Performance'],'https://www.cloudflare.com/',{badges:['Popular'],featured:true,popular:true,pricing:'freemium',pricingLabel:'Freemium',useCases:['Developer','Business']}),
brand('nordvpn','NordVPN','security','VPN service focused on encrypted internet access and privacy.',['VPN','Privacy','Security'],'https://nordvpn.com/',{popular:true,useCases:['Business','Creator']}),
brand('proton','Proton','security','Privacy-focused suite including email, VPN, drive and related services.',['Privacy','Email','VPN','Security'],'https://proton.me/',{popular:true,pricing:'freemium',pricingLabel:'Freemium',useCases:['Business','Creator']}),
brand('1password','1Password','security','Password manager for individuals, families and organizations.',['Passwords','Security','Identity'],'https://1password.com/',{popular:true,useCases:['Business']}),
brand('bitwarden','Bitwarden','security','Open-source password manager for individuals and organizations.',['Passwords','Security','Open Source'],'https://bitwarden.com/',{pricing:'freemium',pricingLabel:'Freemium',popular:true,useCases:['Business','Developer','Creator']}),
brand('malwarebytes','Malwarebytes','security','Security software for protecting devices and digital environments from malware threats.',['Security','Malware','Protection'],'https://www.malwarebytes.com/',{useCases:['Business','Creator']}),
brand('lastpass','LastPass','security','Password management service for storing and managing credentials.',['Passwords','Security','Identity'],'https://www.lastpass.com/',{useCases:['Business','Creator']}),
brand('hotjar','Hotjar','analytics','Product experience platform for understanding how users interact with websites and products.',['Analytics','Heatmaps','UX'],'https://www.hotjar.com/',{pricing:'freemium',pricingLabel:'Freemium',useCases:['Business','Marketing','Designer']}),
brand('google-analytics','Google Analytics','analytics','Web and app analytics platform for measuring user activity and traffic.',['Analytics','Web','Data'],'https://analytics.google.com/',{pricing:'free',pricingLabel:'Free',popular:true,useCases:['Marketing','Business','Developer']}),
brand('mixpanel','Mixpanel','analytics','Product analytics platform for understanding user behavior and product engagement.',['Analytics','Product','Data'],'https://mixpanel.com/',{pricing:'freemium',pricingLabel:'Freemium',useCases:['Business','Developer']}),
brand('amplitude','Amplitude','analytics','Digital analytics platform for product and customer behavior insights.',['Analytics','Product','Data'],'https://www.amplitude.com/',{pricing:'freemium',pricingLabel:'Freemium',useCases:['Business','Developer']}),
brand('matomo','Matomo','analytics','Web analytics platform with an emphasis on data ownership and privacy.',['Analytics','Privacy','Web'],'https://matomo.org/',{useCases:['Business','Developer']}),
brand('typeform','Typeform','business','Online form and survey platform designed for interactive data collection.',['Forms','Surveys','Leads'],'https://www.typeform.com/',{pricing:'freemium',pricingLabel:'Freemium',useCases:['Business','Marketing','Creator']}),
brand('docusign','DocuSign','business','Electronic agreement and signature platform for businesses and individuals.',['E-Signature','Documents','Business'],'https://www.docusign.com/',{popular:true,useCases:['Business']}),
brand('dropbox','Dropbox','business','Cloud file storage, sharing and collaboration service.',['Storage','Files','Collaboration'],'https://www.dropbox.com/',{pricing:'freemium',pricingLabel:'Freemium',popular:true,useCases:['Business','Creator','Student']}),
brand('pcloud','pCloud','business','Cloud storage and file management service.',['Cloud Storage','Files','Privacy'],'https://www.pcloud.com/',{useCases:['Business','Creator']}),
brand('canva-pro','Canva Pro','digital-products','Paid Canva plan for expanded design resources and workflow features.',['Design','Templates','Creator'],'https://www.canva.com/',{pricing:'paid',pricingLabel:'Premium',useCases:['Creator','Business']}),
brand('motion','Motion','productivity','Productivity platform combining calendar, tasks and planning workflows.',['Calendar','Tasks','Planning'],'https://www.usemotion.com/',{useCases:['Business','Creator']}),
brand('todoist','Todoist','productivity','Task management app for personal and team productivity.',['Tasks','To-Do','Productivity'],'https://todoist.com/',{pricing:'freemium',pricingLabel:'Freemium',popular:true,useCases:['Business','Creator','Student']}),
brand('evernote','Evernote','productivity','Note-taking and organization platform for capturing information and tasks.',['Notes','Organization','Productivity'],'https://evernote.com/',{useCases:['Business','Student','Creator']}),
brand('grammarly-business','Grammarly Business','ai','Writing assistance for teams and business communication workflows.',['Writing','AI','Teams'],'https://www.grammarly.com/business', {useCases:['Business','Agency']}),
brand('webex','Webex','business','Video meetings and collaboration platform for teams and organizations.',['Meetings','Video','Collaboration'],'https://www.webex.com/',{pricing:'freemium',pricingLabel:'Freemium',useCases:['Business','Agency']}),
brand('zoom','Zoom','business','Video communications platform for meetings, webinars and collaboration.',['Video','Meetings','Communication'],'https://zoom.us/',{badges:['Popular'],popular:true,pricing:'freemium',pricingLabel:'Freemium',useCases:['Business','Creator','Student']}),
brand('calendly','Calendly','business','Scheduling platform for booking meetings and managing availability.',['Scheduling','Calendar','Meetings'],'https://calendly.com/',{pricing:'freemium',pricingLabel:'Freemium',popular:true,useCases:['Business','Agency','Creator']}),
brand('stripe','Stripe','business','Online payments and financial infrastructure for internet businesses.',['Payments','Finance','Business'],'https://stripe.com/',{useCases:['Business','Developer','Ecommerce']}),
brand('wise','Wise','business','International money transfer and multi-currency financial service.',['Finance','Payments','International'],'https://wise.com/',{useCases:['Business','Creator']}),
brand('freshbooks','FreshBooks','business','Accounting and invoicing software for small businesses and professionals.',['Accounting','Invoices','Finance'],'https://www.freshbooks.com/',{useCases:['Business','Agency']}),
brand('quickbooks','QuickBooks','business','Accounting and financial management software for businesses.',['Accounting','Finance','Invoices'],'https://quickbooks.intuit.com/',{popular:true,useCases:['Business']}),
brand('xero','Xero','business','Online accounting platform for small businesses and accountants.',['Accounting','Finance','Business'],'https://www.xero.com/',{useCases:['Business','Agency']}),
brand('elevenlabs','ElevenLabs','ai','AI audio platform for speech generation and related creator workflows.',['AI','Audio','Voice'],'https://elevenlabs.io/',{pricing:'freemium',pricingLabel:'Freemium',useCases:['Creator','Developer']}),
brand('runway','Runway','ai','AI creative platform for generating and editing video and visual content.',['AI','Video','Creative'],'https://runwayml.com/',{pricing:'freemium',pricingLabel:'Freemium',useCases:['Creator','Agency']}),
brand('midjourney','Midjourney','ai','Generative AI platform focused on creating visual imagery from prompts.',['AI','Image','Creative'],'https://www.midjourney.com/',{useCases:['Creator','Designer']}),
brand('notebooklm','NotebookLM','ai','AI-powered research and note-taking tool from Google designed around user-provided sources.',['AI','Research','Notes'],'https://notebooklm.google/',{pricing:'free',pricingLabel:'Free',useCases:['Student','Research','Business']}),
brand('clickfunnels','ClickFunnels','ecommerce','Platform for creating marketing funnels and online sales experiences.',['Funnels','Marketing','Ecommerce'],'https://www.clickfunnels.com/',{useCases:['Marketing','Ecommerce','Business']}),
brand('tilda','Tilda','development','Website builder for landing pages, websites and content-rich pages.',['Website Builder','Landing Pages','Design'],'https://tilda.cc/',{useCases:['Creator','Marketing','Business']}),
brand('carrd','Carrd','development','Simple website builder for one-page sites and lightweight landing pages.',['Website Builder','Landing Pages','No-Code'],'https://carrd.co/',{pricing:'freemium',pricingLabel:'Freemium',useCases:['Creator','Marketing']}),
brand('framer','Framer','development','Website design and publishing platform combining visual design with web publishing.',['Website Builder','Design','Publishing'],'https://www.framer.com/',{popular:true,pricing:'freemium',pricingLabel:'Freemium',useCases:['Designer','Creator','Marketing']}),
brand('sentry','Sentry','analytics','Application monitoring and error tracking platform for developers.',['Monitoring','Errors','Developer'],'https://sentry.io/',{pricing:'freemium',pricingLabel:'Freemium',useCases:['Developer','Business']}),
brand('grafana','Grafana','analytics','Observability and visualization platform for metrics, logs and telemetry.',['Observability','Dashboards','Developer'],'https://grafana.com/',{useCases:['Developer','Business']}),
brand('twilio','Twilio','business','Communications APIs and customer engagement infrastructure for software teams.',['SMS','Communications','API'],'https://www.twilio.com/',{useCases:['Developer','Business']}),
brand('intercom','Intercom','crm','Customer communications and support platform with messaging and automation.',['Support','CRM','Messaging'],'https://www.intercom.com/',{useCases:['Business','Agency']}),
brand('drift','Drift','crm','Conversational marketing and sales platform for business websites and teams.',['Chat','Marketing','Sales'],'https://www.drift.com/',{useCases:['Business','Marketing']}),
brand('beehiiv','beehiiv','crm','Publishing and newsletter platform for creators and media businesses.',['Newsletter','Creator','Publishing'],'https://www.beehiiv.com/',{pricing:'freemium',pricingLabel:'Freemium',popular:true,useCases:['Creator','Business']}),
brand('buffer','Buffer','seo','Social media publishing and management platform for creators and businesses.',['Social Media','Marketing','Scheduling'],'https://buffer.com/',{pricing:'freemium',pricingLabel:'Freemium',popular:true,useCases:['Creator','Marketing','Business']}),
brand('hootsuite','Hootsuite','seo','Social media management platform for publishing, monitoring and reporting.',['Social Media','Marketing','Analytics'],'https://www.hootsuite.com/',{useCases:['Marketing','Agency','Business']}),
brand('later','Later','seo','Social media marketing platform with publishing and content planning tools.',['Social Media','Creator','Marketing'],'https://later.com/',{pricing:'freemium',pricingLabel:'Freemium',useCases:['Creator','Marketing']}),
brand('sproutsocial','Sprout Social','seo','Social media management platform with publishing and analytics capabilities.',['Social Media','Analytics','Marketing'],'https://sproutsocial.com/',{useCases:['Marketing','Agency','Business']}),
brand('semrush-content','Semrush Content Toolkit','seo','Content-focused tools within the Semrush ecosystem for marketing workflows.',['SEO','Content','Marketing'],'https://www.semrush.com/',{useCases:['Marketing','Agency']}),
brand('surfer-ai','Surfer AI','ai','AI content workflow within the Surfer ecosystem for SEO-oriented content.',['AI','SEO','Content'],'https://surferseo.com/ai-articles/',{useCases:['Marketing','Agency','Creator']})
];

export const collections = [
  {id:'website-launch',title:'Tools to Launch a Website',description:'Core services for building, hosting and publishing a web presence.',brands:['hostinger','cloudways','webflow','wordpress','elementor','cloudflare']},
  {id:'seo-toolkit',title:'SEO Toolkit',description:'A starting set for search research, optimization and site analysis.',brands:['semrush','ahrefs','se-ranking','mangools','moz','screaming-frog']},
  {id:'ai-productivity',title:'AI Productivity Stack',description:'AI assistants and automation tools for knowledge work.',brands:['chatgpt','claude','gemini','perplexity','zapier','make','notion']},
  {id:'creator-toolkit',title:'Creator Toolkit',description:'Design, media, publishing and creator-business tools.',brands:['canva','envato','figma','descript','gumroad','beehiiv','loom']},
  {id:'small-business',title:'Small Business Tools',description:'Business operations, communication, CRM and finance tools.',brands:['hubspot','pipedrive','quickbooks','calendly','stripe','zoom','dropbox']},
  {id:'developer-toolkit',title:'Developer Toolkit',description:'Coding, deployment, APIs, containers and monitoring tools.',brands:['github','vercel','netlify','replit','cursor','postman','docker','sentry']}
];

export const faqs = [
  {q:'What is AGS Digital Store?',a:'AGS Digital Store is a discovery platform that organizes and explains third-party digital products, software, SaaS, AI tools, hosting and online services.'},
  {q:'Are these products sold by AGS?',a:'No. AGS Digital Store does not operate the underlying third-party products. Visitors are directed to the relevant company website or offer.'},
  {q:'How do affiliate links work?',a:'Some outbound links may contain affiliate tracking. When a tracked purchase or sign-up qualifies, AGS may earn a commission at no additional cost to the visitor.'},
  {q:'Are these official websites?',a:'The Visit Official action is designed to send you to the company website stored in the brand data. Always review the destination and terms before signing up.'},
  {q:'Do I need an account to use AGS Digital Store?',a:'No account is required for browsing, search or saving tools on the current static version. Saved and recent data stays in your browser.'},
  {q:'Can I save tools?',a:'Yes. Save and compare data uses localStorage on your device, so it persists across normal refreshes without a backend account.'},
  {q:'How are categories organized?',a:'Categories are data-driven. Each brand references a category and optional subcategory, so new categories can be added to StoreData.js without changing the rendering architecture.'}
];

export const storeMeta = {
  name:'AGS Digital Store',
  tagline:'Discover Better Digital Tools, Software & Services.',
  disclosure:'Some links on AGS Digital Store may be affiliate links. If you purchase or sign up through these links, we may earn a commission at no additional cost to you.'
};

export function getCategory(id){return categories.find(c=>c.id===id)||null;}
